defaults: &defaults
  docker:
    - image: circleci/node:8.1
    # - image: mongo:3
    # - image: redis:3.2

version: 2
jobs:
  server-lint:
    <<: *defaults
    working_directory: ~/alumni-network
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific yarn.lock checksum
            - v3-server-deps-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            # Find a cache corresponding to this specific package.json checksum
            - v3-server-deps-{{ .Branch }}-{{ checksum "package.json" }}
            # Find the most recent cache used from this branch
            - v3-server-deps-{{ .Branch }}
            # Find the most recent cache used from master
            - v3-server-deps-master
      - run:
          name: Install dependencies
          command: yarn
          no_output_timeout: 3m
      - run:
          name: Run linter
          command: npm run lint
          no_output_timeout: 1m
      - save_cache:
          paths:
            - node_modules
          # Save cache for this specific set of packages
          key: v3-server-deps-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

  client-lint:
    <<: *defaults
    working_directory: ~/alumni-network/client
    steps:
      - checkout:
          path: ~/alumni-network
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific yarn.lock checksum
            - v3-client-deps-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            # Find a cache corresponding to this specific package.json checksum
            - v3-client-deps-{{ .Branch }}-{{ checksum "package.json" }}
            # Find the most recent cache used from this branch
            - v3-client-deps-{{ .Branch }}
            # Find the most recent cache used from master
            - v3-client-deps-master
      - run:
          name: Install dependencies
          command: yarn
          no_output_timeout: 3m
      - run:
          name: Run linter
          command: npm run lint
          no_output_timeout: 1m
      - save_cache:
          paths:
            - node_modules
          # Save cache for this specific set of packages
          key: v3-client-deps-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

workflows:
  version: 2
  checkout_lint:
    jobs:
      - server-lint
      - client-lint
